package practica1.enums;

public enum NOMBRE {
    ISLA, LANA, DULCE, BRISA, ESTRELLA, PERLA, ESMERALDA, CELESTE, LUNA , SERENA, SIERRA, ALESSANDRO, ANDRE, JAYDEN, ELIAN, ESTEBAN
    , JUSTO, LUTY, TERESA, LEONEL, RONALDINHO, ANDRES;
}
