package ejercicio6.enums;

public enum APELLIDO {
    ROJAS, CHAMORRO, APONTE, ABENTE, OCAMPO, VALIENTE, GONZALEZ, RODRIGUEZ, ARCE, FRANCO, AYALA, PAVON, ANTONIOLLI,
    SOSA, MESSI, MOREIRA, PEREIRA;
}
