package ejercicio6.enums;

public enum NOMBRE {
    ESTEBAN, ALBERTO, JUSTO, ROLANDO, JULIO, JUAN, RAMON, PEDRO, JOSEFA, RONALDO, LIONEL, RONALDINHO, ZINEDINE,
    CARLOS,ROBERTO,JULIA, PABLO, ARNALDO, MARIA, LUCY, ELVIRA, ANA, ARACELI, NEREA, AGOSTINA;
}
